# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageantparticipant',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=b'/profile/'),
        ),
    ]
